### ISSUE TITLE
Validate that slang codegen was run

### ISSUE THREAD

**Issue by Vorkytaka** [Vorkytaka/mini_tools#39]
We need to check whenever our PR or master branch has updated strings.
So we need to check it.

Maybe something like this:
- Run `dart slang`
- Check if there are changes in the `strings.dart`

**Comment by Vorkytaka** [comment]
Yaml that ChatGPT 4o give me:

```yaml
yaml
   name: Check changes on PR

   on:
     pull_request:

   jobs:
     check-changes:
       runs-on: ubuntu-latest

       steps:
       - uses: actions/checkout@v2

       - name: Cache dependencies
         uses: actions/cache@v2
         with:
           path: path/to/dependencies
           key: ${{ runner.os }}-dependencies-${{ hashFiles('**/lockfiles') }}
           restore-keys: ${{ runner.os }}-dependencies

       - name: Run custom command
         run: your-custom-command

       - name: Check for changes
         run: |
           git diff --exit-code
         id: check_diff
         continue-on-error: true

       - name: Condition to fail the job
         if: steps.check_diff.outcome == 'failure'
         run: exit 1
```
