### ISSUE TITLE
Text Diff

### ISSUE THREAD

**Issue by Vorkytaka** [Vorkytaka/mini_tools#8]

**Comment by Vorkytaka** [comment]
We got a problem with `diff_match_patch`.
It count wrong diff with some cases, specific with line-by-line diffs.
The problem is because of this check on screenshot.

<img width="708" alt="Image" src="https://github.com/user-attachments/assets/cee2c2ab-f7bf-44c2-8a77-f13c11ace008" />

And here is example of wrong diffs.
(Well, it not actually __wrong__, but not what we expect)

Without cleanup

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/88270710-592a-41c5-8e46-54a2cf1c7549" />

With cleanup

<img width="554" alt="Image" src="https://github.com/user-attachments/assets/8e844a94-dab4-4bcf-b39b-676efbabb216" />

Before:
```
name: mini_tools
description: "-"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  convert: ^3.1.1
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.6
  desktop_drop: ^0.4.4
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hsvcolor_picker: ^1.5.1
  flutter_popup: ^3.3.0
  flutter_timezone: ^2.1.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_path: ^0.7.4
  macos_ui: ^2.0.8
  meta: ^1.15.0
  mini_tea: ^0.1.2
  mini_tea_flutter: ^0.2.0
  path: ^1.9.0
  pointycastle: ^3.9.1
  provider: ^6.1.2
  re_editor: ^0.3.1
  re_highlight: ^0.0.3
  responsive_grid: ^2.4.4
  rxdart: ^0.28.0
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  syntax_highlight: ^0.4.0
  timezone: ^0.9.4
  uuid: ^4.5.1
  window_manager: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  mini_tea_test: ^0.2.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
```

After:
```
name: mini_tools
description: "-"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  convert: ^3.1.1
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.6
  desktop_drop: ^0.4.4
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hsvcolor_picker: ^1.5.1
  flutter_popup: ^3.3.0
  flutter_timezone: ^2.1.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_path: ^0.7.4
  macos_ui: ^2.0.8
  meta: ^1.15.0
  mini_tea: ^0.1.2
  mini_tea_flutter: ^0.2.0
  path: ^1.9.0
  pointycastle: ^3.9.1
  provider: ^6.1.2
  re_editor: ^0.3.1
  re_highlight: ^0.0.3
  responsive_grid: ^2.4.4
  rxdart: ^0.28.0
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  syntax_highlight: ^0.4.0
  timezone: ^0.9.4
  window_manager: ^0.4.0

  diff_match_patch: ^0.4.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  mini_tea_test: ^0.2.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
```
